### ISSUE TITLE
Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by ebell451** [huacat1017/huacat.office-theme#1]
As [VSCodium ](https://vscodium.com) has made the move to the https://open-vsx.org marketplace, could you please publish this extension there?

Here is a guide on [How to Publish an Extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) on their marketplace.

Thank you,

**Comment by huacat1017** [comment]
OK! I published and you can see Office Theme on [https://open-vsx.org](https://open-vsx.org).
