### ISSUE TITLE
Make it obvious that it's not from Microsoft

### ISSUE THREAD

**Issue by prashantvc** [huacat1017/huacat.office-theme#12]
As a PM I love this extension! But could you make sure at that it is not from the **Microsoft**
Something like "Unofficial Office Theme"

**Comment by huacat1017** [comment]
OK!(Thank you for your suggestion)
I would declare that in README.md, but not change the extension name(I think adding unofficial makes the name ugly).
Maybe update with some patches next weekend...

**Comment by huacat1017** [comment]
v.1.1.2 is here. You can see the changes in README.md
