### ISSUE TITLE
Add Clippy

### ISSUE THREAD

**Issue by spartanatreyu** [huacat1017/huacat.office-theme#13]
Hello. It looks like you're trying to make an office theme in VS Code.

![](https://cdn.vox-cdn.com/thumbor/vpkc7-RDy4UocmN2BKz22o94mTU=/0x0:1062x705/1820x1213/filters:focal(447x269:615x437):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/63280536/clippy.0.jpg)

**Comment by huacat1017** [comment]
Thank you for your good idea.
If I made it, I would separate to other extension...
But I don't want to make it for now...
Or you can ask someone to make it first.
