### ISSUE TITLE
Excel preview: Only up to column Z?

### ISSUE THREAD

**Issue by cbsteh** [huacat1017/huacat.office-theme#8]
In VS Code, the preview of Excel files is only up to column Z even though there are data beyond column Z. Is this an intentional limit (such as to save memory)?

**Comment by huacat1017** [comment]
Do you mean this extension? [Excel Viewer](https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer)

**Comment by cbsteh** [comment]
> Do you mean this extension? [Excel Viewer](https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer)

I was referring to Office Theme. It was only when I realized that the preview was up to column Z did I disable yours and tried the Excel Viewer. The funny thing is after I installed Excel Viewer, yours failed to work even though I disabled Excel Viewer and re-enabled yours.

**Comment by huacat1017** [comment]
When I install Excel Viewer, my extension still works well. It's just a theme

**Comment by cbsteh** [comment]
Oops, sorry. Got confused between the two.

**Comment by huacat1017** [comment]
It's OK. Closed. (Probably [this Extension](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office)'s bug
