### ISSUE TITLE
Color improvements

### ISSUE THREAD

**Issue by nonameolsson** [huacat1017/huacat.office-theme#9]
Lovely theme, great work! 

Just wanted to report some things that could be improved. I don't have any experience on creating themes so I can't help you.

**1. GitLens hoverbox comments**
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1493018/128459553-746192f3-d9c8-48b4-ae58-d1c03aa10d73.png">

**2. Install buttons** 
<img width="271" alt="image" src="https://user-images.githubusercontent.com/1493018/128459574-d9734ade-96cb-4e44-be4d-969b2ad8d143.png">

**Comment by huacat1017** [comment]
Hoverbox comments looks like Link elements.
Links & Install Button will be improved soon
Thank you!

**Comment by huacat1017** [comment]
Updated! Hope you'll like it!
